version: '3'

services:
  openvpn:
    build: .
    tty: true
    stdin_open: true
    environment:
      - OVPN_DEFROUTE=0
      - EXTERNAL_ADDRESS=87.13.169.118
      - CLIENT_FORWARD=192.168.255.2:1000,192.168.255.3:2000
    ports:
      - 1194:1194/udp
    cap_add:
      - NET_ADMIN
    volumes:
      - ./openvpn:/etc/openvpn
    restart: always
