version: '3'

services:
  openvpn:
    build: .
    tty: true
    stdin_open: true
    environment:
      - DNS_IP=0.0.0.0
      - EXTERNAL_ADDRESS=0.0.0.0
    ports:
      - 1194:1194/udp
    cap_add:
      - NET_ADMIN
    volumes:
      - openvpn:/etc/openvpn
    restart: always

volumes:
  openvpn:
