version: '3'

services:
  openvpn:
    build: .
    tty: true
    stdin_open: true
    environment:
      - EXTERNAL_PORT=5000
      - EXTERNAL_ADDRESS=87.16.175.17
      - CLIENT_FORWARD=192.168.255.2:1000,192.168.255.3:2000
    ports:
      - 5000:5000/udp
    cap_add:
      - NET_ADMIN
    volumes:
      - ./openvpn:/etc/openvpn
    restart: always

  adminer:
    image: adminer
    ports:
      - 8080:8080
